export const emptyProduct = {
  product_id: null,
  name: "",
  rating: null,
  description: "",
  category: "",
  power_total_max_kw: null,
  power_total_min_kw: null,
  power_nominal_max_kw: null,
  power_nominal_min_kw: null,
  efficiency_max_percent: null,
  efficiency_min_percent: null,
  pellet_consumption_max_kg_h: null,
  pellet_consumption_min_kg_h: null,
  heating_volume_m3: null,
  exhaust_diameter_mm: null,
  air_inlet_diameter_mm: null,
  pellet_tank_capacity_kg: null,
  weight_kg: null,
  dimensions_mm_WxDxH: "",
  electrical_power_max_w: null,
  electrical_power_min_w: null,
  energy_class: "",
  price_eur: null,
  image: "",
  images: [],
  water_heating: null,
};
