// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgvswatqmbvaqfznixyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndnN3YXRxbWJ2YXFmem5peHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NjMzMzgsImV4cCI6MjA3ODAzOTMzOH0.SQ81o9TvS2Dh2krc0XsOp63HUQ3qj9Marp6Y3FIgJfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});